version: "3.8"

networks:
    nginx_reverse_proxy_gateway:
        external: true
        name: nginx_reverse_proxy_gateway

services:
    automationid-api:
        container_name: ${AUTOMATIONID_API}
        depends_on:
            - ${AUTOMATIONID_DB}
        image: ${AUTOMATIONID_API}
        build:
            context: ./automationid-api
            dockerfile: Dockerfile
        restart: always
        command: bash -c 'while !</dev/tcp/automationid-db/${MY_SQL_PORT}; do sleep 1; done; npm start'
        networks:
            - ${HOST_NETWORK}
        ports:
            - "${AUTOMATIONID_API_PORT}:${AUTOMATIONID_API_PORT}"
volumes:
    mysql-data:
        driver: local
